"use strict";

const { Stock } = require("../models");

module.exports = {
  async up(queryInterface, Sequelize) {
    const yesterday = new Date(0);
    await Stock.bulkCreate([
      {
        id: 1,
        symbol: "NVDA",
        name: "NVIDIA Corp",
        price: "105.38",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Semiconductors",
        ipo: "1999-01-22T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/NVDA.png",
        marketCap: "2928146.167374",
        outstandingShares: "24600",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 2,
        symbol: "MSFT",
        name: "Microsoft Corp",
        price: "405.63",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "1986-03-13T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/MSFT.png",
        marketCap: "3100617.819732",
        outstandingShares: "7432.31",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 3,
        symbol: "AAPL",
        name: "Apple Inc",
        price: "221.66",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "1980-12-12T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AAPL.png",
        marketCap: "3481747.308594",
        outstandingShares: "15334.08",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 4,
        symbol: "GOOGL",
        name: "Alphabet Inc",
        price: "156.63",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Media",
        ipo: "2004-08-19T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/GOOG.png",
        marketCap: "2020869.886246",
        outstandingShares: "12358",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 5,
        symbol: "AMC",
        name: "AMC Entertainment Holdings Inc",
        price: "4.63",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Media",
        ipo: "2013-12-18T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AMC.png",
        marketCap: "1741.731068",
        outstandingShares: "295.59",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 6,
        symbol: "WMT",
        name: "Walmart Inc",
        price: "77.33",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Retail",
        ipo: "1972-08-25T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/WMT.png",
        marketCap: "621202.888188",
        outstandingShares: "8043.54",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 7,
        symbol: "BAC",
        name: "Bank of America Corp",
        price: "40.66",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Banking",
        ipo: "1979-06-05T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/BAC.png",
        marketCap: "316202.788696",
        outstandingShares: "7820.37",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 8,
        symbol: "AMZN",
        name: "Amazon.com Inc",
        price: "174.49",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Retail",
        ipo: "1997-05-15T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AMZN.png",
        marketCap: "1873458.777832",
        outstandingShares: "10406.63",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 9,
        symbol: "META",
        name: "Meta Platforms, Inc.",
        price: "512.63810",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Media",
        ipo: "2012-05-18T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/FB.png",
        marketCap: "1303361.59786418",
        outstandingShares: "2529.82",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 10,
        symbol: "LLY",
        name: "Eli Lilly & Co",
        price: "946.31000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Pharmaceuticals",
        ipo: "1970-07-09T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/LLY.png",
        marketCap: "897724.641525085",
        outstandingShares: "950.43",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 11,
        symbol: "AVGO",
        name: "Broadcom Inc",
        price: "154.12500",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Semiconductors",
        ipo: "2009-08-06T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AVGO.png",
        marketCap: "721181.038099947",
        outstandingShares: "4654.88",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 12,
        symbol: "TSLA",
        name: "Tesla Inc",
        price: "219.43000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Automobiles",
        ipo: "2013-03-06T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/TSLA.png",
        marketCap: "699370.692447081",
        outstandingShares: "3189.2",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 13,
        symbol: "JPM",
        name: "JPMorgan Chase & Co",
        price: "219.33000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Banking",
        ipo: "1969-03-05T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/JPM.png",
        marketCap: "623095.081950133",
        outstandingShares: "2845.16",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 14,
        symbol: "UNH",
        name: "UnitedHealth Group Inc",
        price: "604.18000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Health Care",
        ipo: "1984-10-17T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/UNH.png",
        marketCap: "556895.012208461",
        outstandingShares: "923.42",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 15,
        symbol: "V",
        name: "Visa Inc",
        price: "280.49000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Financial Services",
        ipo: "2008-03-25T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/V.png",
        marketCap: "554538.289152831",
        outstandingShares: "1975.91",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 16,
        symbol: "XOM",
        name: "Exxon Mobil Corp",
        price: "114.06000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Energy",
        ipo: "1980-03-17T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/XOM.png",
        marketCap: "508525.944897801",
        outstandingShares: "4443",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 17,
        symbol: "MA",
        name: "Mastercard Inc",
        price: "483.00000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Financial Services",
        ipo: "2006-05-25T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/MA.png",
        marketCap: "445916.661839483",
        outstandingShares: "923.83",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 18,
        symbol: "PG",
        name: "Procter & Gamble Co-The",
        price: "175.92000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Consumer products",
        ipo: "1950-03-22T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/PG.png",
        marketCap: "412444.213854407",
        outstandingShares: "2349.71",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 19,
        symbol: "JNJ",
        name: "Johnson & Johnson",
        price: "167.36000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Pharmaceuticals",
        ipo: "1944-09-25T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/JNJ.png",
        marketCap: "402298.567992797",
        outstandingShares: "2407.24",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 20,
        symbol: "COST",
        name: "Costco Wholesale Corp",
        price: "890.02000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Retail",
        ipo: "1985-12-05T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/COST.png",
        marketCap: "394794.273708488",
        outstandingShares: "443.34",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 21,
        symbol: "ORCL",
        name: "Oracle Corp",
        price: "140.71000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "1986-03-12T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/ORCL.png",
        marketCap: "386853.862578992",
        outstandingShares: "2755.86",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 22,
        symbol: "HD",
        name: "Home Depot Inc-The",
        price: "364.67000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Retail",
        ipo: "1984-04-19T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/HD.png",
        marketCap: "361826.975671382",
        outstandingShares: "993.29",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 23,
        symbol: "ABBV",
        name: "AbbVie Inc",
        price: "197.01000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Biotechnology",
        ipo: "2013-01-02T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/ABBV.png",
        marketCap: "349082.519623691",
        outstandingShares: "1766.34",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 24,
        symbol: "KO",
        name: "Coca-Cola Co-The",
        price: "72.56000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Beverages",
        ipo: "1950-01-26T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/KO.png",
        marketCap: "312228.408281056",
        outstandingShares: "4309.87",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 25,
        symbol: "MRK",
        name: "Merck & Co Inc",
        price: "115.80000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Pharmaceuticals",
        ipo: "1941-01-01T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/MRK.png",
        marketCap: "292263.519897545",
        outstandingShares: "2534.81",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 26,
        symbol: "NFLX",
        name: "Netflix Inc",
        price: "679.53000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Media",
        ipo: "2002-05-23T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/NFLX.png",
        marketCap: "292355.520032177",
        outstandingShares: "429.16",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 27,
        symbol: "CVX",
        name: "Chevron Corp",
        price: "142.07000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Energy",
        ipo: "1921-06-24T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/CVX.png",
        marketCap: "259669.65845571",
        outstandingShares: "1828.92",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 28,
        symbol: "ADBE",
        name: "Adobe Inc",
        price: "575.21500",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "1986-08-20T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/ADBE.png",
        marketCap: "256103.392620271",
        outstandingShares: "443.4",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 29,
        symbol: "PEP",
        name: "PepsiCo Inc",
        price: "178.51000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Beverages",
        ipo: "1919-12-18T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/PEP.png",
        marketCap: "244439.559297679",
        outstandingShares: "1373.57",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 30,
        symbol: "CRM",
        name: "salesforce.com Inc",
        price: "247.68000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "2004-06-23T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/CRM.png",
        marketCap: "236944.597667976",
        outstandingShares: "956",
        createdAt: yesterday,
        updatedAt: yesterday,
      },

      {
        id: 31,
        symbol: "TMO",
        name: "Thermo Fisher Scientific Inc",
        price: "611.90000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Life Sciences Tools & Services",
        ipo: "1980-08-27T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/TMO.png",
        marketCap: "232933.449878417",
        outstandingShares: "382",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 32,
        symbol: "TMUS",
        name: "T-Mobile US Inc",
        price: "198.77000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Telecommunication",
        ipo: "2007-04-19T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/TMUS.png",
        marketCap: "232388.379341298",
        outstandingShares: "1166.78",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 33,
        symbol: "AMD",
        name: "Advanced Micro Devices Inc",
        price: "140.87000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Semiconductors",
        ipo: "1979-10-15T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AMD.png",
        marketCap: "228027.92368968",
        outstandingShares: "1618.48",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 34,
        symbol: "LIN",
        name: "Linde plc",
        price: "472.14999",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Chemicals",
        ipo: "2018-10-31T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/950838588696.png",
        marketCap: "225858.793317",
        outstandingShares: "480.72",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 35,
        symbol: "ACN",
        name: "Accenture PLC",
        price: "343.99000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "2001-07-19T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/ACN.png",
        marketCap: "215423.01479222",
        outstandingShares: "626.38",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 36,
        symbol: "MCD",
        name: "McDonald's Corp",
        price: "288.03000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Hotels, Restaurants & Leisure",
        ipo: "1965-04-21T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/MCD.png",
        marketCap: "206056.844000022",
        outstandingShares: "717.34",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 37,
        symbol: "CSCO",
        name: "Cisco Systems Inc",
        price: "49.70000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Communications",
        ipo: "1990-02-16T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/950800186156.png",
        marketCap: "200594.689279897",
        outstandingShares: "4028.81",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 38,
        symbol: "ABT",
        name: "Abbott Laboratories",
        price: "114.40000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Health Care",
        ipo: "1937-03-01T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/ABT.png",
        marketCap: "199444.396345153",
        outstandingShares: "1739.9",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 39,
        symbol: "WFC",
        name: "Wells Fargo & Co",
        price: "58.12000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Banking",
        ipo: "1962-12-10T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/WFC.png",
        marketCap: "197299.539723438",
        outstandingShares: "3403.77",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 40,
        symbol: "PM",
        name: "Philip Morris International Inc",
        price: "126.56000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Tobacco",
        ipo: "2008-03-17T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/PM.png",
        marketCap: "196184.853566103",
        outstandingShares: "1554.8",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 41,
        symbol: "DHR",
        name: "Danaher Corp",
        price: "264.49000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Life Sciences Tools & Services",
        ipo: "1969-12-10T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/DHR.png",
        marketCap: "190722.036440436",
        outstandingShares: "722.21",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 42,
        symbol: "IBM",
        name: "International Business Machines Corp",
        price: "204.11000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "1915-11-11T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/IBM.png",
        marketCap: "187527.348066879",
        outstandingShares: "921.15",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 43,
        symbol: "TXN",
        name: "Texas Instruments Inc",
        price: "203.96000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Semiconductors",
        ipo: "1953-10-01T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/TXN.png",
        marketCap: "186663.117647841",
        outstandingShares: "913.05",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 44,
        symbol: "QCOM",
        name: "QUALCOMM Inc",
        price: "165.32000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Semiconductors",
        ipo: "1991-12-13T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/QCOM.png",
        marketCap: "184271.425000499",
        outstandingShares: "1114",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 45,
        symbol: "GE",
        name: "General Electric Co",
        price: "166.36000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Aerospace & Defense",
        ipo: "1892-06-23T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/GE.png",
        marketCap: "180071.540970851",
        outstandingShares: "1084.31",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 46,
        symbol: "AXP",
        name: "American Express Co",
        price: "251.74000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Financial Services",
        ipo: "1977-05-18T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AXP.png",
        marketCap: "178961.335218255",
        outstandingShares: "710.91",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 47,
        symbol: "AMGN",
        name: "Amgen Inc",
        price: "330.61000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Biotechnology",
        ipo: "1983-06-17T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AMGN.png",
        marketCap: "177756.57236805",
        outstandingShares: "537.33",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 48,
        symbol: "VZ",
        name: "Verizon Communications Inc",
        price: "41.48000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Telecommunication",
        ipo: "1984-02-15T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/VZ.png",
        marketCap: "174189.939646349",
        outstandingShares: "4209.52",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 49,
        symbol: "INTU",
        name: "Intuit Inc",
        price: "623.10000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "1993-03-12T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/INTU.png",
        marketCap: "174363.245536324",
        outstandingShares: "279.55",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 50,
        symbol: "NOW",
        name: "ServiceNow Inc",
        price: "834.83000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Technology",
        ipo: "2012-06-29T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/NOW.png",
        marketCap: "172083.126983823",
        outstandingShares: "206",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 51,
        symbol: "ISRG",
        name: "Intuitive Surgical Inc",
        price: "481.55000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Health Care",
        ipo: "2000-06-13T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/ISRG.png",
        marketCap: "171445.958702913",
        outstandingShares: "354.71",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 52,
        symbol: "NEE",
        name: "NextEra Energy Inc",
        price: "81.08000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Utilities",
        ipo: "1950-02-15T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/NEE.png",
        marketCap: "166247.269745914",
        outstandingShares: "2054.53",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 53,
        symbol: "GS",
        name: "Goldman Sachs Group Inc-The",
        price: "490.64000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Financial Services",
        ipo: "1999-05-04T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/GS.png",
        marketCap: "154691.254026928",
        outstandingShares: "315.8",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 54,
        symbol: "CAT",
        name: "Caterpillar Inc",
        price: "336.75000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Machinery",
        ipo: "1929-12-02T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/CAT.png",
        marketCap: "163245.800543101",
        outstandingShares: "484.9",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 55,
        symbol: "DIS",
        name: "Walt Disney Co-The",
        price: "89.25000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Media",
        ipo: "1957-11-12T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/DIS.png",
        marketCap: "161518.089075748",
        outstandingShares: "1813.59",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 56,
        symbol: "MS",
        name: "Morgan Stanley",
        price: "100.15000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Financial Services",
        ipo: "1986-03-21T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/MS.png",
        marketCap: "162012.86017769",
        outstandingShares: "1617.86",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 57,
        symbol: "RTX",
        name: "Raytheon Technologies Corp",
        price: "121.11000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Aerospace & Defense",
        ipo: "1934-09-05T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/RTX.png",
        marketCap: "160759.426220105",
        outstandingShares: "1330.24",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 58,
        symbol: "PFE",
        name: "Pfizer Inc",
        price: "28.39000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Pharmaceuticals",
        ipo: "1944-01-17T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/PFE.png",
        marketCap: "160310.792255285",
        outstandingShares: "5666.7",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 59,
        symbol: "SPGI",
        name: "S&P Global Inc",
        price: "513.17000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Financial Services",
        ipo: "1929-02-14T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/SPGI.png",
        marketCap: "160506.396164039",
        outstandingShares: "313",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 60,
        symbol: "UNP",
        name: "Union Pacific Corp",
        price: "255.70000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Road & Rail",
        ipo: "1969-06-20T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/UNP.png",
        marketCap: "155418.503922692",
        outstandingShares: "609.2",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 61,
        symbol: "AMAT",
        name: "Applied Materials Inc",
        price: "182.32000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Semiconductors",
        ipo: "1972-10-05T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AMAT.png",
        marketCap: "150029.167541371",
        outstandingShares: "824.4",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 62,
        symbol: "UBER",
        name: "Uber Technologies Inc",
        price: "71.56000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Road & Rail",
        ipo: "2019-05-10T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/UBER.png",
        marketCap: "150437.610928165",
        outstandingShares: "2100.94",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 63,
        symbol: "CMCSA",
        name: "Comcast Corp",
        price: "38.67000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Media",
        ipo: "1972-06-29T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/CMCSA.png",
        marketCap: "149807.720678323",
        outstandingShares: "3872.5",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 64,
        symbol: "PGR",
        name: "Progressive Corp-The",
        price: "253.91000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Insurance",
        ipo: "1987-01-06T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/PGR.png",
        marketCap: "148126.822778406",
        outstandingShares: "585.67",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 65,
        symbol: "T",
        name: "AT&T Inc",
        price: "20.57000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Telecommunication",
        ipo: "1983-11-21T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/T.png",
        marketCap: "147456.072954443",
        outstandingShares: "7170.24",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 66,
        symbol: "LOW",
        name: "Lowe's Cos Inc",
        price: "245.45000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Retail",
        ipo: "1979-12-19T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/LOW.png",
        marketCap: "138899.149615943",
        outstandingShares: "567.29",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 67,
        symbol: "SYK",
        name: "Stryker Corp",
        price: "360.30000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Health Care",
        ipo: "1980-03-17T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/SYK.png",
        marketCap: "136950.867636421",
        outstandingShares: "380.95",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 68,
        symbol: "LMT",
        name: "Lockheed Martin Corp",
        price: "574.78000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Aerospace & Defense",
        ipo: "1961-10-11T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/LMT.png",
        marketCap: "136965.267867541",
        outstandingShares: "238.36",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 69,
        symbol: "HON",
        name: "Honeywell International Inc",
        price: "205.50000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Industrial Conglomerates",
        ipo: "1985-09-19T00:00:00.000Z",
        logo: "",
        marketCap: "133650.360405773",
        outstandingShares: "651.19",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 70,
        symbol: "TJX",
        name: "TJX Cos Inc-The",
        price: "117.52000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Retail",
        ipo: "1965-11-17T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/TJX.png",
        marketCap: "132028.805605877",
        outstandingShares: "1127.87",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 71,
        symbol: "BLK",
        name: "BlackRock Inc",
        price: "886.49000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Financial Services",
        ipo: "1999-10-01T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/BLK.png",
        marketCap: "130886.322966881",
        outstandingShares: "148.13",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 72,
        symbol: "BKNG",
        name: "Booking Holdings Inc",
        price: "3795.75000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Hotels, Restaurants & Leisure",
        ipo: "1999-03-29T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/BKNG.png",
        marketCap: "127537.163056264",
        outstandingShares: "33.52",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 73,
        symbol: "REGN",
        name: "Regeneron Pharmaceuticals Inc",
        price: "1178.94000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Biotechnology",
        ipo: "1991-04-02T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/REGN.png",
        marketCap: "130095.092523813",
        outstandingShares: "110.23",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 74,
        symbol: "ELV",
        name: "Elevance Health, Inc.",
        price: "547.31000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Health Care",
        ipo: "2001-10-30T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/ANTM.png",
        marketCap: "126701.280187122",
        outstandingShares: "231.89",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 75,
        symbol: "COP",
        name: "ConocoPhillips",
        price: "108.56000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Energy",
        ipo: "1980-03-17T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/COP.png",
        marketCap: "126233.652957013",
        outstandingShares: "1161.25",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 76,
        symbol: "VRTX",
        name: "Vertex Pharmaceuticals Inc",
        price: "478.44000",
        currency: "USD",
        exchange: "NASDAQ",
        country: "United States",
        type: "Common Stock",
        industry: "Biotechnology",
        ipo: "1991-07-24T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/VRTX.png",
        marketCap: "123691.999758635",
        outstandingShares: "258.1",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 77,
        symbol: "NKE",
        name: "NIKE Inc",
        price: "81.02000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Textiles, Apparel & Luxury Goods",
        ipo: "1980-12-02T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/NKE.png",
        marketCap: "121006.566159455",
        outstandingShares: "1499.36",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
      {
        id: 78,
        symbol: "BSX",
        name: "Boston Scientific Corp",
        price: "81.96000",
        currency: "USD",
        exchange: "NYSE",
        country: "United States",
        type: "Common Stock",
        industry: "Health Care",
        ipo: "1992-05-19T00:00:00.000Z",
        logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/BSX.png",
        marketCap: "120585.987179227",
        outstandingShares: "1472.63",
        createdAt: yesterday,
        updatedAt: yesterday,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
