"use strict";

const { Stock } = require("../models");

module.exports = {
  async up(queryInterface, Sequelize) {
    const yesterday = new Date(0);
    await Stock.bulkCreate([
      // {
      //   symbol: "AAPL",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "AMC",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "NVDA",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "GOOG",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "JPM",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "AMZN",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "NFLX",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "META",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "MSFT",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "LLY",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "AVGO",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "TSLA",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "WMT",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "XOM",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "UNH",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "V",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "MA",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "PG",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "JNJ",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "COST",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "ORCL",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "HD",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
      // {
      //   symbol: "ABBV",
      //   name: "Apple Inc",
      //   price: "5",
      //   currency: "USD",
      //   exchange: "NASDAQ",
      //   country: "Unites States",
      //   type: "Common Stock",
      //   industry: "Technology",
      //   ipo: new Date(),
      //   logo: "x",
      //   marketCap: "213",
      //   outstandingShares: "22",
      //   updatedAt: yesterday,
      // },
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
